language: node_js

node_js:
  - 12.9
  - "node"
  - "lts/*"
  - "lts/dubnium"

script:
  - npm i
  - npx lerna bootstrap
  - npm run test

cache: npm

notifications:
  email:
    on_success: never
    on_failure: always

after_success:
  - 'cat ./packages/api-explorer/coverage/lcov.info | ./node_modules/.bin/coveralls'
  - 'cat ./packages/api-logs/coverage/lcov.info | ./node_modules/.bin/coveralls'
  - 'cat ./packages/markdown/coverage/lcov.info | ./node_modules/.bin/coveralls'
  - 'cat ./packages/syntax-highlighter/coverage/lcov.info | ./node_modules/.bin/coveralls'
  - 'cat ./packages/variable/coverage/lcov.info | ./node_modules/.bin/coveralls'
