language: node_js

node_js:
  - "node"
  - "lts/*"
  - "lts/carbon"

script:
  - npm i
  - npx lerna bootstrap
  - npm run test

cache: npm

notifications:
  email:
    on_success: never
    on_failure: always
