name: github ci

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs: 
  node-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
      - uses: actions/setup-node@v2
      - run: npm i
      - run: npx lerna bootstrap
      - run: npm run test

