name: github ci

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs: 
  node-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
      - name: Launch test
        run: |
          npm i
          npx lerna bootstrap
          npm run test

